# Generated by Django 4.2 on 2025-11-14 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=100, unique=True, verbose_name='合同编号')),
                ('name', models.CharField(max_length=200, verbose_name='合同名称')),
                ('vendor', models.CharField(max_length=200, verbose_name='维保厂商')),
                ('contact_person', models.CharField(max_length=100, verbose_name='联系人')),
                ('contact_phone', models.CharField(max_length=50, verbose_name='联系电话')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='联系邮箱')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('contract_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='合同金额')),
                ('status', models.CharField(choices=[('active', '有效'), ('expired', '已过期'), ('terminated', '已终止')], default='active', max_length=20, verbose_name='合同状态')),
                ('service_scope', models.TextField(verbose_name='服务范围')),
                ('response_time', models.CharField(blank=True, max_length=100, verbose_name='响应时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_contracts', to='contracts.contract', verbose_name='关联合同')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_maintenance_contracts', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '维保合同',
                'verbose_name_plural': '维保合同',
                'db_table': 'assets_maintenance_contract',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='资产名称')),
                ('asset_type', models.CharField(choices=[('server', '服务器'), ('storage', '存储设备'), ('network', '网络设备'), ('security', '安全设备'), ('other', '其他设备')], default='server', max_length=20, verbose_name='资产类型')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='设备厂商')),
                ('model', models.CharField(max_length=100, verbose_name='设备型号')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='序列号')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='采购日期')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='采购价格')),
                ('residual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='残值')),
                ('status', models.CharField(choices=[('in_use', '使用中'), ('idle', '闲置'), ('maintenance', '维护中'), ('retired', '已退役'), ('damaged', '损坏')], default='in_use', max_length=20, verbose_name='资产状态')),
                ('data_center', models.CharField(blank=True, max_length=100, verbose_name='数据中心')),
                ('machine_room', models.CharField(blank=True, max_length=100, verbose_name='机房')),
                ('cabinet', models.CharField(blank=True, max_length=50, verbose_name='机柜')),
                ('u_position_start', models.IntegerField(blank=True, null=True, verbose_name='起始U位')),
                ('u_position_end', models.IntegerField(blank=True, null=True, verbose_name='结束U位')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('current_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_assets', to=settings.AUTH_USER_MODEL, verbose_name='当前使用人')),
                ('purchase_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_assets', to='contracts.contract', verbose_name='采购合同')),
            ],
            options={
                'verbose_name': '有形资产',
                'verbose_name_plural': '有形资产',
                'db_table': 'assets_physical_asset',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('routine', '例行维护'), ('repair', '故障维修'), ('upgrade', '升级改造'), ('inspection', '巡检')], default='routine', max_length=20, verbose_name='记录类型')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('in_progress', '处理中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('scheduled_date', models.DateField(verbose_name='计划日期')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='实际日期')),
                ('technician', models.CharField(blank=True, max_length=100, verbose_name='技术人员')),
                ('description', models.TextField(verbose_name='维护描述')),
                ('result', models.TextField(blank=True, verbose_name='维护结果')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='费用')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_history', to='assets.physicalasset', verbose_name='资产')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_maintenance_records', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('maintenance_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='assets.maintenancecontract', verbose_name='维保合同')),
            ],
            options={
                'verbose_name': '维保记录',
                'verbose_name_plural': '维保记录',
                'db_table': 'assets_maintenance_record',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='IntangibleAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='资产名称')),
                ('asset_type', models.CharField(choices=[('software_license', '软件许可'), ('patent', '专利'), ('trademark', '商标'), ('copyright', '著作权'), ('domain', '域名'), ('other', '其他')], default='software_license', max_length=30, verbose_name='资产类型')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='购买日期')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='购买价格')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='有效期开始')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='有效期结束')),
                ('status', models.CharField(choices=[('active', '有效'), ('expired', '已过期'), ('suspended', '暂停'), ('terminated', '已终止')], default='active', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_intangible_assets', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '无形资产',
                'verbose_name_plural': '无形资产',
                'db_table': 'assets_intangible_asset',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetUsageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='开始使用日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束使用日期')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_history', to='assets.physicalasset', verbose_name='资产')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_usage_history', to=settings.AUTH_USER_MODEL, verbose_name='使用人')),
            ],
            options={
                'verbose_name': '资产使用历史',
                'verbose_name_plural': '资产使用历史',
                'db_table': 'assets_usage_history',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='assets.physicalasset', verbose_name='资产')),
                ('maintenance_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_records', to='assets.maintenancecontract', verbose_name='维保合同')),
            ],
            options={
                'verbose_name': '资产维保',
                'verbose_name_plural': '资产维保',
                'db_table': 'assets_maintenance',
                'ordering': ['-created_at'],
            },
        ),
    ]
