# Generated by Django 4.2 on 2025-11-13 03:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationSystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='系统名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='系统编码')),
                ('description', models.TextField(blank=True, verbose_name='系统描述')),
                ('system_type', models.CharField(choices=[('application', '应用系统'), ('database', '数据库系统'), ('middleware', '中间件系统'), ('monitoring', '监控系统'), ('backup', '备份系统'), ('other', '其他系统')], default='application', max_length=20, verbose_name='系统类型')),
                ('operation_mode', models.CharField(choices=[('7x24', '7x24小时'), ('5x8', '5x8小时')], default='7x24', max_length=10, verbose_name='运行模式')),
                ('status', models.CharField(choices=[('running', '运行中'), ('stopped', '已停止'), ('maintenance', '维护中'), ('error', '异常')], default='stopped', max_length=20, verbose_name='系统状态')),
                ('service_content', models.TextField(verbose_name='服务内容')),
                ('product_content', models.TextField(verbose_name='产品内容')),
                ('total_cpu', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='CPU总量(核)')),
                ('total_memory', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='内存总量(GB)')),
                ('total_storage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='存储总量(GB)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_start_time', models.DateTimeField(blank=True, null=True, verbose_name='最后启动时间')),
                ('last_stop_time', models.DateTimeField(blank=True, null=True, verbose_name='最后停止时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_information_systems', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='information_systems', to='tenants.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '信息系统',
                'verbose_name_plural': '信息系统',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='资源名称')),
                ('resource_type', models.CharField(choices=[('compute', '计算资源'), ('storage', '存储资源'), ('network', '网络资源'), ('database', '数据库资源')], max_length=20, verbose_name='资源类型')),
                ('status', models.CharField(choices=[('active', '活跃'), ('inactive', '非活跃'), ('error', '错误'), ('maintenance', '维护')], default='inactive', max_length=20, verbose_name='资源状态')),
                ('region', models.CharField(max_length=100, verbose_name='区域')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('cpu_cores', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='CPU核数')),
                ('memory_gb', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='内存大小(GB)')),
                ('storage_gb', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='存储容量(GB)')),
                ('openstack_resource_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='OpenStack资源ID')),
                ('openstack_resource_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='OpenStack资源类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='启动时间')),
                ('running_time', models.DurationField(blank=True, null=True, verbose_name='运行时间')),
                ('information_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='information_systems.informationsystem', verbose_name='信息系统')),
            ],
            options={
                'verbose_name': '系统资源',
                'verbose_name_plural': '系统资源',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('start', '启动'), ('stop', '停止'), ('restart', '重启'), ('maintenance', '维护'), ('update', '更新'), ('delete', '删除')], max_length=20, verbose_name='操作类型')),
                ('operation_detail', models.TextField(verbose_name='操作详情')),
                ('operation_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('information_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to='information_systems.informationsystem', verbose_name='信息系统')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
            ],
            options={
                'verbose_name': '系统操作日志',
                'verbose_name_plural': '系统操作日志',
                'ordering': ['-operation_time'],
            },
        ),
        migrations.CreateModel(
            name='SystemBillingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_period', models.DateField(verbose_name='计费周期')),
                ('base_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='基础费用')),
                ('discount_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=5, verbose_name='折扣率')),
                ('actual_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='实际费用')),
                ('running_hours', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='运行小时数')),
                ('cpu_usage_hours', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='CPU使用小时数')),
                ('memory_usage_hours', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='内存使用小时数')),
                ('storage_usage_hours', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='存储使用小时数')),
                ('is_paid', models.BooleanField(default=False, verbose_name='是否已支付')),
                ('paid_date', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('information_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to='information_systems.informationsystem', verbose_name='信息系统')),
            ],
            options={
                'verbose_name': '系统计费记录',
                'verbose_name_plural': '系统计费记录',
                'ordering': ['-billing_period'],
            },
        ),
    ]
