# Generated by Django 4.2 on 2025-11-13 06:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('information_systems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceAdjustmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('cpu_upgrade', 'CPU升级'), ('cpu_downgrade', 'CPU降级'), ('memory_upgrade', '内存升级'), ('memory_downgrade', '内存降级'), ('storage_upgrade', '存储升级'), ('storage_downgrade', '存储降级')], max_length=20, verbose_name='调整类型')),
                ('old_cpu_cores', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='调整前CPU核数')),
                ('old_memory_gb', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='调整前内存大小(GB)')),
                ('old_storage_gb', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='调整前存储容量(GB)')),
                ('new_cpu_cores', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='调整后CPU核数')),
                ('new_memory_gb', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='调整后内存大小(GB)')),
                ('new_storage_gb', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='调整后存储容量(GB)')),
                ('adjustment_detail', models.TextField(verbose_name='调整详情')),
                ('adjustment_date', models.DateTimeField(verbose_name='调整时间')),
                ('effective_date', models.DateField(verbose_name='生效日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('information_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_adjustments', to='information_systems.informationsystem', verbose_name='信息系统')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
            ],
            options={
                'verbose_name': '资源调整日志',
                'verbose_name_plural': '资源调整日志',
                'ordering': ['-adjustment_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyBillingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_date', models.DateField(verbose_name='计费日期')),
                ('cpu_cores', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='CPU核数')),
                ('memory_gb', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='内存大小(GB)')),
                ('storage_gb', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='存储容量(GB)')),
                ('running_hours', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='运行小时数')),
                ('cpu_usage_hours', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='CPU使用小时数')),
                ('memory_usage_hours', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='内存使用小时数')),
                ('storage_usage_hours', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='存储使用小时数')),
                ('hourly_rate', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='小时费率')),
                ('daily_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='日费用')),
                ('discount_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=5, verbose_name='折扣率')),
                ('actual_daily_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实际日费用')),
                ('is_processed', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('information_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_billing_records', to='information_systems.informationsystem', verbose_name='信息系统')),
            ],
            options={
                'verbose_name': '每日计费记录',
                'verbose_name_plural': '每日计费记录',
                'ordering': ['-billing_date'],
                'unique_together': {('information_system', 'billing_date')},
            },
        ),
    ]
