# Generated by Django 4.2 on 2025-11-19 01:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('information_systems', '0002_resourceadjustmentlog_dailybillingrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='虚拟机名称')),
                ('cpu_cores', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)], verbose_name='CPU核数')),
                ('memory_gb', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)], verbose_name='内存大小(GB)')),
                ('disk_gb', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(10)], verbose_name='磁盘容量(GB)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('mac_address', models.CharField(blank=True, max_length=17, verbose_name='MAC地址')),
                ('status', models.CharField(choices=[('running', '运行中'), ('stopped', '已停止'), ('paused', '已暂停'), ('error', '异常')], default='stopped', max_length=20, verbose_name='状态')),
                ('runtime_start', models.TimeField(blank=True, null=True, verbose_name='运行开始时间')),
                ('runtime_end', models.TimeField(blank=True, null=True, verbose_name='运行结束时间')),
                ('openstack_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='OpenStack实例ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_start_time', models.DateTimeField(blank=True, null=True, verbose_name='最后启动时间')),
                ('last_stop_time', models.DateTimeField(blank=True, null=True, verbose_name='最后停止时间')),
                ('os_type', models.CharField(blank=True, max_length=50, verbose_name='操作系统类型')),
                ('os_version', models.CharField(blank=True, max_length=50, verbose_name='操作系统版本')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vms', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('information_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_machines', to='information_systems.informationsystem', verbose_name='所属信息系统')),
            ],
            options={
                'verbose_name': '虚拟机',
                'verbose_name_plural': '虚拟机',
                'ordering': ['-created_at'],
                'unique_together': {('information_system', 'name')},
            },
        ),
        migrations.CreateModel(
            name='VMOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('start', '启动'), ('stop', '停止'), ('restart', '重启'), ('pause', '暂停'), ('resume', '恢复'), ('delete', '删除')], max_length=20, verbose_name='操作类型')),
                ('operation_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operation_detail', models.TextField(blank=True, verbose_name='操作详情')),
                ('success', models.BooleanField(default=True, verbose_name='是否成功')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
                ('virtual_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to='information_systems.virtualmachine', verbose_name='虚拟机')),
            ],
            options={
                'verbose_name': '虚拟机操作日志',
                'verbose_name_plural': '虚拟机操作日志',
                'ordering': ['-operation_time'],
            },
        ),
    ]
