# Generated by Django 4.2 on 2025-11-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_systems', '0003_virtualmachine_vmoperationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='availability_zone',
            field=models.CharField(blank=True, max_length=100, verbose_name='可用区'),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='data_center_type',
            field=models.CharField(choices=[('production', '生产环境'), ('local_dr', '同城灾备'), ('remote_dr', '异地灾备'), ('development', '开发环境'), ('testing', '测试环境')], default='production', max_length=20, verbose_name='数据中心类型'),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='区域'),
        ),
    ]
