# Generated by Django 4.2 on 2025-11-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productsubscription_contract_and_more'),
        ('services', '0001_initial'),
        ('information_systems', '0004_virtualmachine_availability_zone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationsystem',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='information_systems', to='products.product', verbose_name='订阅产品'),
        ),
        migrations.AddField(
            model_name='informationsystem',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='information_systems', to='services.service', verbose_name='订阅服务'),
        ),
        migrations.AlterField(
            model_name='informationsystem',
            name='product_content',
            field=models.TextField(blank=True, default='', verbose_name='产品内容备注'),
        ),
        migrations.AlterField(
            model_name='informationsystem',
            name='service_content',
            field=models.TextField(blank=True, default='', verbose_name='服务内容备注'),
        ),
    ]
