# Generated by Django 4.2 on 2025-12-02 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('information_systems', '0005_informationsystem_products_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VMSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='快照名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('openstack_image_id', models.CharField(blank=True, max_length=64, verbose_name='OpenStack镜像ID')),
                ('size_gb', models.IntegerField(default=0, verbose_name='大小(GB)')),
                ('status', models.CharField(choices=[('creating', '创建中'), ('available', '可用'), ('restoring', '恢复中'), ('deleting', '删除中'), ('error', '错误')], default='creating', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('virtual_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='information_systems.virtualmachine', verbose_name='虚拟机')),
            ],
            options={
                'verbose_name': '虚拟机快照',
                'verbose_name_plural': '虚拟机快照',
                'db_table': 'vm_snapshots',
                'ordering': ['-created_at'],
            },
        ),
    ]
