# Generated by Django 4.2 on 2025-11-13 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='服务名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='服务编码')),
                ('description', models.TextField(blank=True, verbose_name='服务描述')),
                ('service_type', models.CharField(choices=[('compute', '计算服务'), ('storage', '存储服务'), ('network', '网络服务'), ('security', '安全服务'), ('monitoring', '监控服务'), ('backup', '备份服务'), ('other', '其他服务')], default='other', max_length=20, verbose_name='服务类型')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用'), ('draft', '草稿')], default='active', max_length=20, verbose_name='状态')),
                ('availability', models.CharField(choices=[('99.999%', '99.999%'), ('99.99%', '99.99%'), ('99.75%', '99.75%'), ('99.9%', '99.9%')], default='99.9%', max_length=10, verbose_name='可用性')),
                ('mttr', models.CharField(choices=[('<=30min', '<=30分钟'), ('<=2h', '<=2小时'), ('<=4h', '<=4小时'), ('<=8h', '<=8小时'), ('<=24h', '<=24小时')], default='<=4h', max_length=10, verbose_name='平均响应时间')),
                ('rpo', models.CharField(choices=[('0', '0'), ('1h', '1小时')], default='1h', max_length=10, verbose_name='本地恢复点目标')),
                ('rto', models.CharField(choices=[('<=1h', '<=1小时'), ('1-4h', '1小时<RTO<=4小时'), ('>4h', '>4小时')], default='1-4h', max_length=10, verbose_name='本地恢复时间目标')),
                ('complaint_rate', models.DecimalField(decimal_places=4, default=0.0001, help_text='投诉总数/统计次数', max_digits=5, verbose_name='事件平均客户投诉率')),
                ('network_availability', models.DecimalField(decimal_places=2, default=99.9, help_text='[(周期时长-网络节点中断时长-计划内停用时长)/(周期时长-计划内停用时长)]*100%', max_digits=5, verbose_name='信息网络运行率')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='基础价格')),
                ('billing_unit', models.CharField(choices=[('month', '月'), ('quarter', '季度'), ('year', '年'), ('instance', '实例'), ('user', '用户'), ('gb', 'GB'), ('request', '请求数')], default='month', max_length=20, verbose_name='计费单位')),
                ('billing_period', models.CharField(choices=[('monthly', '按月'), ('quarterly', '按季度'), ('yearly', '按年'), ('usage', '按使用量')], default='monthly', max_length=20, verbose_name='计费周期')),
                ('features', models.TextField(blank=True, verbose_name='服务特性')),
                ('specifications', models.TextField(blank=True, verbose_name='技术规格')),
                ('service_level', models.CharField(blank=True, max_length=100, verbose_name='服务等级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_services', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '服务',
                'verbose_name_plural': '服务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', '活跃'), ('suspended', '暂停'), ('terminated', '终止'), ('expired', '过期')], default='active', max_length=20, verbose_name='状态')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('discount_rate', models.DecimalField(decimal_places=4, default=1.0, help_text='1.0表示无折扣，0.8表示20%折扣', max_digits=5, verbose_name='折扣率')),
                ('monthly_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='月费用')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_subscriptions', to='contracts.contract', verbose_name='合同')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='services.service', verbose_name='服务')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_subscriptions', to='tenants.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '服务订阅',
                'verbose_name_plural': '服务订阅',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'service', 'contract')},
            },
        ),
    ]
