# Generated by Django 4.2 on 2025-11-21 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage', models.FloatField(default=0.0, verbose_name='CPU使用率')),
                ('memory_usage', models.FloatField(default=0.0, verbose_name='内存使用率')),
                ('disk_usage', models.FloatField(default=0.0, verbose_name='磁盘使用率')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
            ],
            options={
                'verbose_name': '系统指标',
                'verbose_name_plural': '系统指标',
                'db_table': 'system_metrics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', '用户登录'), ('logout', '用户登出'), ('create', '创建'), ('update', '更新'), ('delete', '删除'), ('system', '系统操作')], max_length=20, verbose_name='操作类型')),
                ('description', models.TextField(verbose_name='描述')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '活动日志',
                'verbose_name_plural': '活动日志',
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
