# Generated by Django 4.2 on 2025-12-02 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information_systems', '0006_vmsnapshot'),
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VMMetricHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage', models.FloatField(verbose_name='CPU使用率(%)')),
                ('memory_usage', models.FloatField(verbose_name='内存使用率(%)')),
                ('network_in_rate', models.FloatField(default=0, verbose_name='网络入流量(KB/s)')),
                ('network_out_rate', models.FloatField(default=0, verbose_name='网络出流量(KB/s)')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='采集时间')),
                ('virtual_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information_systems.virtualmachine', verbose_name='虚拟机')),
            ],
            options={
                'verbose_name': '虚拟机监控历史',
                'verbose_name_plural': '虚拟机监控历史',
                'db_table': 'vm_metric_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='vmmetrichistory',
            index=models.Index(fields=['virtual_machine', 'timestamp'], name='vm_metric_h_virtual_a6f848_idx'),
        ),
    ]
