# Generated by Django 4.2 on 2025-12-03 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information_systems', '0006_vmsnapshot'),
        ('monitoring', '0002_vmmetrichistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('metric_type', models.CharField(choices=[('cpu', 'CPU使用率'), ('memory', '内存使用率'), ('disk', '磁盘使用率'), ('network_in', '网络入流量'), ('network_out', '网络出流量')], max_length=20, verbose_name='指标类型')),
                ('threshold', models.FloatField(verbose_name='阈值')),
                ('operator', models.CharField(choices=[('gt', '大于'), ('lt', '小于')], default='gt', max_length=10, verbose_name='比较操作符')),
                ('duration', models.IntegerField(default=5, help_text='持续超过该时间才触发告警', verbose_name='持续时间(分钟)')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('virtual_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='information_systems.virtualmachine', verbose_name='关联虚拟机')),
            ],
            options={
                'verbose_name': '告警规则',
                'verbose_name_plural': '告警规则',
                'db_table': 'alert_rules',
            },
        ),
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_value', models.FloatField(verbose_name='触发值')),
                ('message', models.TextField(verbose_name='告警内容')),
                ('status', models.CharField(choices=[('active', '触发中'), ('resolved', '已恢复')], default='active', max_length=20, verbose_name='状态')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='恢复时间')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.alertrule', verbose_name='触发规则')),
                ('virtual_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information_systems.virtualmachine', verbose_name='虚拟机')),
            ],
            options={
                'verbose_name': '告警历史',
                'verbose_name_plural': '告警历史',
                'db_table': 'alert_history',
                'ordering': ['-started_at'],
            },
        ),
    ]
