# Generated by Django 4.2 on 2025-12-04 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitoring', '0003_alertrule_alerthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='changes',
            field=models.JSONField(blank=True, help_text='记录变更前后的值', null=True, verbose_name='变更详情'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='错误信息'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='request_method',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='请求方法'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='request_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='请求路径'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='resource_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='资源ID'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='resource_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='资源名称'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='resource_type',
            field=models.CharField(choices=[('vm', '虚拟机'), ('image', '镜像'), ('network', '网络'), ('snapshot', '快照'), ('tenant', '租户'), ('user', '用户'), ('system', '信息系统'), ('alert_rule', '告警规则'), ('other', '其他')], default='other', max_length=20, verbose_name='资源类型'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='status',
            field=models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('partial', '部分成功')], default='success', max_length=20, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='用户代理'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('login', '用户登录'), ('logout', '用户登出'), ('create', '创建'), ('update', '更新'), ('delete', '删除'), ('start', '启动'), ('stop', '停止'), ('restart', '重启'), ('resize', '调整配置'), ('snapshot', '创建快照'), ('restore', '恢复快照'), ('upload', '上传'), ('download', '下载'), ('read', '查看'), ('execute', '执行'), ('system', '系统操作')], max_length=20, verbose_name='操作类型'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='description',
            field=models.TextField(verbose_name='操作描述'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作用户'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'created_at'], name='activity_lo_user_id_d23b30_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['resource_type', 'resource_id'], name='activity_lo_resourc_31a457_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action_type', 'created_at'], name='activity_lo_action__9b73de_idx'),
        ),
    ]
