# Generated by Django 4.2 on 2025-11-20 02:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('compute', '计算资源'), ('storage', '存储资源'), ('network', '网络资源'), ('database', '数据库资源'), ('product', '产品订阅'), ('service', '服务订阅'), ('other', '其他费用')], max_length=20, verbose_name='费用类型')),
                ('name', models.CharField(max_length=200, verbose_name='费用项名称')),
                ('description', models.TextField(blank=True, verbose_name='费用描述')),
                ('billing_date', models.DateField(verbose_name='计费日期')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='数量')),
                ('unit', models.CharField(max_length=50, verbose_name='单位')),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='单价')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='金额')),
                ('discount_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=5, verbose_name='折扣率')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='折扣金额')),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='最终金额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '账单明细',
                'verbose_name_plural': '账单明细',
                'ordering': ['billing_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bill_number', models.CharField(max_length=100, unique=True, verbose_name='账单编号')),
                ('billing_year', models.IntegerField(verbose_name='账期年份')),
                ('billing_month', models.IntegerField(verbose_name='账期月份')),
                ('billing_period_start', models.DateField(verbose_name='账期开始日期')),
                ('billing_period_end', models.DateField(verbose_name='账期结束日期')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='账单总金额')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='已支付金额')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='折扣金额')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待支付'), ('partial_paid', '部分支付'), ('paid', '已支付'), ('overdue', '已逾期'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='账单状态')),
                ('due_date', models.DateField(verbose_name='到期日期')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付完成时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '月度账单',
                'verbose_name_plural': '月度账单',
                'ordering': ['-billing_year', '-billing_month'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_number', models.CharField(max_length=100, unique=True, verbose_name='支付编号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='支付金额')),
                ('payment_method', models.CharField(choices=[('bank_transfer', '银行转账'), ('alipay', '支付宝'), ('wechat', '微信支付'), ('check', '支票'), ('cash', '现金'), ('other', '其他')], default='bank_transfer', max_length=20, verbose_name='支付方式')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('failed', '失败'), ('refunded', '已退款')], default='pending', max_length=20, verbose_name='支付状态')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='支付时间')),
                ('transaction_id', models.CharField(blank=True, max_length=200, verbose_name='交易流水号')),
                ('payer_account', models.CharField(blank=True, max_length=200, verbose_name='付款账号')),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='payments/', verbose_name='支付凭证')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.monthlybill', verbose_name='账单')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_confirmed_payments', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_created_payments', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '支付记录',
                'verbose_name_plural': '支付记录',
                'ordering': ['-payment_date'],
            },
        ),
    ]
