# Generated by Django 4.2 on 2025-11-20 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('information_systems', '0005_informationsystem_products_and_more'),
        ('billing', '0001_initial'),
        ('tenants', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='订单'),
        ),
        migrations.AddField(
            model_name='monthlybill',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_bills', to='tenants.tenant', verbose_name='租户'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.monthlybill', verbose_name='月度账单'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='information_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_items', to='information_systems.informationsystem', verbose_name='关联信息系统'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlybill',
            unique_together={('tenant', 'billing_year', 'billing_month')},
        ),
    ]
