# Generated by Django 4.2 on 2025-11-13 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='数据中心名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='数据中心代码')),
                ('data_center_type', models.CharField(choices=[('production', '生产中心'), ('same_city', '同城灾备'), ('different_city', '异地灾备')], max_length=20, verbose_name='数据中心类型')),
                ('location', models.CharField(max_length=200, verbose_name='位置')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '数据中心',
                'verbose_name_plural': '数据中心',
                'ordering': ['data_center_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='租户名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='租户编码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('level', models.CharField(choices=[('superior', '上级单位'), ('important', '重要客户'), ('ordinary', '普通客户')], default='ordinary', max_length=20, verbose_name='租户级别')),
                ('discount_level', models.CharField(choices=[('level_a', 'A级(9折)'), ('level_b', 'B级(8.5折)'), ('level_c', 'C级(8折)'), ('level_d', 'D级(7.5折)'), ('level_e', 'E级(7折)'), ('level_f', 'F级(6.5折)'), ('no_discount', '无折扣')], default='no_discount', max_length=20, verbose_name='折扣级别')),
                ('tenant_type', models.CharField(choices=[('virtual', '虚拟资源'), ('virtual_physical', '虚拟+物理资源'), ('virtual_physical_network', '虚拟+物理+网络线路资源'), ('datacenter_cabinet', '机房机柜资源')], default='virtual', max_length=30, verbose_name='租户类型')),
                ('status', models.CharField(choices=[('active', '活跃'), ('suspended', '暂停'), ('terminated', '终止'), ('pending', '待审核')], default='pending', max_length=20, verbose_name='状态')),
                ('contact_person', models.CharField(max_length=100, verbose_name='联系人')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='联系邮箱')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('openstack_project_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='OpenStack项目ID')),
                ('quota_vcpus', models.IntegerField(default=0, verbose_name='vCPU配额')),
                ('quota_memory', models.IntegerField(default=0, verbose_name='内存配额(GB)')),
                ('quota_disk', models.IntegerField(default=0, verbose_name='磁盘配额(GB)')),
                ('quota_instances', models.IntegerField(default=0, verbose_name='实例配额')),
                ('quota_networks', models.IntegerField(default=0, verbose_name='网络配额')),
                ('quota_floating_ips', models.IntegerField(default=0, verbose_name='浮动IP配额')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tenants', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '租户',
                'verbose_name_plural': '租户',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantResourceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_vcpus', models.IntegerField(default=0, verbose_name='已使用vCPU')),
                ('used_memory', models.IntegerField(default=0, verbose_name='已使用内存(GB)')),
                ('used_disk', models.IntegerField(default=0, verbose_name='已使用磁盘(GB)')),
                ('used_instances', models.IntegerField(default=0, verbose_name='已使用实例')),
                ('used_networks', models.IntegerField(default=0, verbose_name='已使用网络')),
                ('used_floating_ips', models.IntegerField(default=0, verbose_name='已使用浮动IP')),
                ('monthly_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='月费用')),
                ('record_date', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_usage', to='tenants.tenant')),
            ],
            options={
                'verbose_name': '租户资源使用情况',
                'verbose_name_plural': '租户资源使用情况',
                'ordering': ['-record_date'],
            },
        ),
        migrations.CreateModel(
            name='TenantOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('suspend', '暂停'), ('activate', '激活'), ('terminate', '终止')], max_length=20, verbose_name='操作类型')),
                ('operation_detail', models.TextField(verbose_name='操作详情')),
                ('operation_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to='tenants.tenant')),
            ],
            options={
                'verbose_name': '租户操作日志',
                'verbose_name_plural': '租户操作日志',
                'ordering': ['-operation_time'],
            },
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stakeholder_type', models.CharField(choices=[('customer', '客户'), ('delivery_team', '项目交付团队'), ('operation_team', '运维团队')], max_length=20, verbose_name='干系人类型')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('phone_encrypted', models.TextField(verbose_name='加密电话号码')),
                ('email_encrypted', models.TextField(verbose_name='加密邮箱')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='职位')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='部门')),
                ('is_primary', models.BooleanField(default=False, verbose_name='主要联系人')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholders', to='tenants.tenant')),
            ],
            options={
                'verbose_name': '干系人',
                'verbose_name_plural': '干系人',
                'ordering': ['tenant', 'stakeholder_type', 'is_primary', '-name'],
            },
        ),
    ]
