# Generated by Django 4.2 on 2025-11-13 07:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_number', models.CharField(max_length=100, unique=True, verbose_name='合同编号')),
                ('title', models.CharField(max_length=200, verbose_name='合同标题')),
                ('description', models.TextField(blank=True, verbose_name='合同描述')),
                ('contract_type', models.CharField(choices=[('standard', '标准合同'), ('custom', '定制合同'), ('trial', '试用合同'), ('upgrade', '升级合同')], default='standard', max_length=20, verbose_name='合同类型')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('active', '生效中'), ('suspended', '暂停'), ('terminated', '已终止'), ('expired', '已过期')], default='draft', max_length=20, verbose_name='合同状态')),
                ('start_date', models.DateField(verbose_name='合同开始日期')),
                ('end_date', models.DateField(verbose_name='合同结束日期')),
                ('signed_date', models.DateField(blank=True, null=True, verbose_name='签署日期')),
                ('billing_method', models.CharField(choices=[('monthly', '按月计费'), ('quarterly', '按季度计费'), ('yearly', '按年计费'), ('pay_as_use', '按使用量计费')], default='monthly', max_length=20, verbose_name='计费方式')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='合同总金额')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='已付金额')),
                ('discount_rate', models.DecimalField(decimal_places=4, default=1.0, help_text='1.0表示无折扣，0.9表示9折', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(2)], verbose_name='折扣率')),
                ('terms_and_conditions', models.TextField(blank=True, verbose_name='合同条款')),
                ('special_terms', models.TextField(blank=True, verbose_name='特殊条款')),
                ('client_contact_person', models.CharField(max_length=100, verbose_name='客户联系人')),
                ('client_contact_phone', models.CharField(max_length=20, verbose_name='客户联系电话')),
                ('client_contact_email', models.EmailField(max_length=254, verbose_name='客户联系邮箱')),
                ('company_contact_person', models.CharField(max_length=100, verbose_name='我方联系人')),
                ('company_contact_phone', models.CharField(max_length=20, verbose_name='我方联系电话')),
                ('company_contact_email', models.EmailField(max_length=254, verbose_name='我方联系邮箱')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='合同文件')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_contracts', to=settings.AUTH_USER_MODEL, verbose_name='审批者')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='tenants.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '合同',
                'verbose_name_plural': '合同',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_period_months', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='续约期限(月)')),
                ('new_total_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='续约金额')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('approved', '已批准'), ('rejected', '已拒绝'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='续约状态')),
                ('renewal_reason', models.TextField(verbose_name='续约原因')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_renewals', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('new_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_from', to='contracts.contract', verbose_name='新合同')),
                ('original_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='contracts.contract', verbose_name='原合同')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_renewals', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '合同续约',
                'verbose_name_plural': '合同续约',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='付款金额')),
                ('payment_date', models.DateField(verbose_name='付款日期')),
                ('payment_method', models.CharField(choices=[('bank_transfer', '银行转账'), ('check', '支票'), ('cash', '现金'), ('online', '在线支付'), ('other', '其他')], default='bank_transfer', max_length=20, verbose_name='付款方式')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('confirmed', '已确认'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='付款状态')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='付款参考号')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='payments/', verbose_name='付款凭证')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contracts.contract', verbose_name='合同')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
            ],
            options={
                'verbose_name': '付款记录',
                'verbose_name_plural': '付款记录',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='ContractItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('vcpu', '虚拟CPU'), ('memory', '内存'), ('storage', '存储'), ('network', '网络'), ('instance', '实例'), ('license', '许可证'), ('support', '技术支持'), ('other', '其他')], max_length=20, verbose_name='项目类型')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='数量')),
                ('unit', models.CharField(max_length=50, verbose_name='单位')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='单价')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='小计')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contracts.contract', verbose_name='合同')),
            ],
            options={
                'verbose_name': '合同项目',
                'verbose_name_plural': '合同项目',
                'ordering': ['id'],
            },
        ),
    ]
