# Generated by Django 4.2 on 2025-11-13 03:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '__first__'),
        ('tenants', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='产品名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='产品编码')),
                ('description', models.TextField(blank=True, verbose_name='产品描述')),
                ('product_type', models.CharField(choices=[('compute', '计算资源'), ('storage', '存储资源'), ('network', '网络资源'), ('database', '数据库服务'), ('middleware', '中间件服务'), ('monitoring', '监控服务'), ('backup', '备份服务'), ('security', '安全服务'), ('other', '其他服务')], default='compute', max_length=20, verbose_name='产品类型')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用'), ('draft', '草稿')], default='draft', max_length=20, verbose_name='产品状态')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='基础价格')),
                ('billing_unit', models.CharField(choices=[('core', '核'), ('gb', 'GB'), ('tb', 'TB'), ('instance', '实例'), ('connection', '连接'), ('request', '请求'), ('user', '用户')], default='core', max_length=20, verbose_name='计费单位')),
                ('billing_period', models.CharField(choices=[('hourly', '按小时'), ('daily', '按天'), ('weekly', '按周'), ('monthly', '按月'), ('quarterly', '按季度'), ('yearly', '按年')], default='monthly', max_length=20, verbose_name='计费周期')),
                ('pricing_model', models.CharField(choices=[('fixed', '固定价格'), ('usage_based', '按使用量'), ('tiered', '阶梯定价'), ('subscription', '订阅制'), ('hybrid', '混合模式')], default='fixed', max_length=20, verbose_name='定价模型')),
                ('min_quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='最小购买量')),
                ('cpu_capacity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='CPU容量(核)')),
                ('memory_capacity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='内存容量(GB)')),
                ('storage_capacity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='存储容量(GB)')),
                ('features', models.TextField(blank=True, verbose_name='产品特性')),
                ('specifications', models.TextField(blank=True, verbose_name='技术规格')),
                ('service_level', models.CharField(blank=True, max_length=100, verbose_name='服务级别')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='订阅数量')),
                ('status', models.CharField(choices=[('active', '生效中'), ('suspended', '已暂停'), ('terminated', '已终止'), ('expired', '已过期')], default='active', max_length=20, verbose_name='订阅状态')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='单价')),
                ('discount_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=5, verbose_name='折扣率')),
                ('monthly_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='月费用')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_subscriptions', to='contracts.contract', verbose_name='合同')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='products.product', verbose_name='产品')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_subscriptions', to='tenants.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '产品订阅',
                'verbose_name_plural': '产品订阅',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='最小数量')),
                ('max_quantity', models.IntegerField(blank=True, help_text='为空表示无上限', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='最大数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='阶梯单价')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_tiers', to='products.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '定价阶梯',
                'verbose_name_plural': '定价阶梯',
                'ordering': ['order', 'min_quantity'],
            },
        ),
        migrations.CreateModel(
            name='DiscountLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='折扣级别名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='折扣级别编码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('discount_rate', models.DecimalField(decimal_places=4, help_text='0.9表示9折，0.8表示8折', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='折扣率')),
                ('customer_type', models.CharField(choices=[('government', '政府机构'), ('enterprise', '企业客户'), ('education', '教育机构'), ('startup', '创业公司'), ('partner', '合作伙伴'), ('other', '其他')], default='enterprise', max_length=20, verbose_name='客户类型')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=20, verbose_name='状态')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, help_text='0表示无限制', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='最小消费金额')),
                ('max_amount', models.DecimalField(decimal_places=2, default=0, help_text='0表示无限制', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='最大消费金额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_discount_levels', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '折扣级别',
                'verbose_name_plural': '折扣级别',
                'ordering': ['discount_rate'],
            },
        ),
    ]
