# Generated by Django 4.2 on 2025-11-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, help_text='根据产品类型选择相应的子类别', max_length=50, verbose_name='子类别'),
        ),
        migrations.AlterField(
            model_name='discountlevel',
            name='customer_type',
            field=models.CharField(choices=[('superior_unit', '上级单位'), ('important_customer', '重要客户'), ('ordinary_customer', '普通客户')], default='ordinary_customer', max_length=20, verbose_name='客户类型'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('ecs', 'ECS计算资源'), ('ods', 'ODS存储资源'), ('net', 'NET网络专线'), ('anq', 'AnQ安全服务'), ('bas', 'BAS基础服务'), ('other', '其他服务')], default='ecs', max_length=20, verbose_name='产品类型'),
        ),
    ]
