# Generated by Django 4.2 on 2025-11-18 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('products', '0002_product_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsubscription',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_subscriptions', to='contracts.contract', verbose_name='合同'),
        ),
        migrations.AlterField(
            model_name='productsubscription',
            name='status',
            field=models.CharField(choices=[('pending', '待审批'), ('active', '生效中'), ('suspended', '已暂停'), ('terminated', '已终止'), ('expired', '已过期')], default='active', max_length=20, verbose_name='订阅状态'),
        ),
    ]
